export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export type GET_TRANSACTIONS = typeof GET_TRANSACTIONS;

export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export type GET_TRANSACTIONS_SUCCESS = typeof GET_TRANSACTIONS_SUCCESS;

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export type ADD_TRANSACTION = typeof ADD_TRANSACTION;

export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS';
export type ADD_TRANSACTION_SUCCESS = typeof ADD_TRANSACTION_SUCCESS;

export const RESET_ADD_TRANSACTION_SUCCESS = 'RESET_ADD_TRANSACTION_SUCCESS';
export type RESET_ADD_TRANSACTION_SUCCESS = typeof RESET_ADD_TRANSACTION_SUCCESS;

export const ADD_TRANSACTION_FAILURE = 'ADD_TRANSACTION_FAILURE';
export type ADD_TRANSACTION_FAILURE = typeof ADD_TRANSACTION_FAILURE;
