export const GET_SUMMARY_REQUEST = "GET_SUMMARY_REQUEST";
export const GET_SUMMARY_SUCCESS = "GET_SUMMARY_SUCCESS";
export const EDIT_INCOME = "EDIT_INCOME";

export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";

export const EDIT_TRANSACTION = "EDIT_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
