export const GET_SUMMARY_REQUEST = "GET_SUMMARY_REQUEST";
export const GET_SUMMARY_SUCCESS = "GET_SUMMARY_SUCCESS";

export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
